=== apertium/apertium-dixtools/schemas/crossmodel.dtd
<!ELEMENT cross-model (cross-action*)>
<!-- Cross action -->
<!ELEMENT cross-action (pattern, constants?, action)>
<!ATTLIST cross-action id CDATA #REQUIRED>
<!ATTLIST cross-action a CDATA #REQUIRED>

<!-- Pattern -->
<!ELEMENT pattern (e,e)>

<!-- Action -->
<!ELEMENT action (e)>

<!-- Element -->
<!ELEMENT e (p)>
<!ATTLIST e r (LR|RL) #IMPLIED>
<!ELEMENT p (l,r)>
<!ELEMENT l (#PCDATA | s)*>
<!ELEMENT r (#PCDATA | s)*>
<!ELEMENT s EMPTY>
<!ATTLIST s n CDATA #REQUIRED>

=== apertium/apertium-dixtools/schemas/cross-model-test.xml
<!DOCTYPE cross-model SYSTEM "crossmodel.dtd">
<cross-model>
   <cross-action id="default" a="ebenimeli">
        <description>Default pattern</description>
        <pattern>
            <e>
                <p>
                    <l>l1<s n="X1"/><s n="S1"/></l>
                    <r>l2<s n="X1"/><s n="S2"/></r>
                </p>
            </e>
            <e>
                <p>
                    <l>l3<s n="X1"/><s n="S3"/></l>
                    <r>l4<s n="X1"/><s n="S4"/></r>
                </p>
            </e>
        </pattern>
        <action-set>
            <action>
                <e>
                    <p>
                        <l>l1<s n="X1"/><s n="S1"/></l>
                        <r>l4<s n="X1"/><s n="S4"/></r>
                    </p>
                </e>
            </action>
        </action-set>
    </cross-action>
</cross-model>

=== apertium/apertium-dixtools/schemas/cross-model.xml
<!--
<!DOCTYPE cross-model SYSTEM "crossmodel.dtd">
-->
<cross-model>
    <cross-action id="default" a="ebenimeli">
        <description>Default pattern</description>
        <pattern>
            <e>
                <p>
                    <l>$lemmaA<s n="$cat"/><s n="@tailA"/></l>
                    <r>$lemmaB<s n="$cat"/><s n="*"/></r>
                </p>
            </e>
            <e>
                <p>
                    <l>$lemmaB<s n="$cat"/><s n="*"/></l>
                    <r>$lemmaC<s n="$cat"/><s n="@tailC"/></r>
                </p>
            </e>
        </pattern>
        <action-set>
            <action>
                <e>
                    <p>
                        <l>$lemmaA<s n="$cat"/><s n="@tailA"/></l>
                        <r>$lemmaC<s n="$cat"/><s n="@tailC"/></r>
                    </p>
                </e>
            </action>
        </action-set>
    </cross-action>
</cross-model>
